name: movie-box

services:
  server:
    type: node
    run:
      - ln -s /user/.cache /home/node/.cache
      - yarn install
    overrides:
      image: luisalejandro/movie-box:latest
      build:
        context: .
        dockerfile: Dockerfile

tooling:
  yarn:
    service: server
  bash:
    service: server