name: Code Quality

on:
  workflow_dispatch:
  schedule:
    - cron: '00 3 1 * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    if: github.repository == 'LuisAlejandro/movie-box'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: javascript
          config-file: ./.github/codeql-config.yml
      - name: Restoring node_modules cache
        uses: actions/cache@v2
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
      - name: Login to Github Docker Registry
        run: echo ${{ secrets.PERSONAL_ACCESS_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
      - name: Pulling docker cache
        run: |
          GITHUB_REPOSITORY=$(echo $GITHUB_REPOSITORY | tr '[A-Z]' '[a-z]')
          docker pull docker.pkg.github.com/$GITHUB_REPOSITORY/moviebox-build-cache || true
      - name: Building image with cache
        run: |
          GITHUB_REPOSITORY=$(echo $GITHUB_REPOSITORY | tr '[A-Z]' '[a-z]')
          docker build . -t luisalejandro/movie-box:latest --cache-from=docker.pkg.github.com/$GITHUB_REPOSITORY/moviebox-build-cache
      - name: Building project
        run: |
          sudo chown -R 1000:1000 .
          make start
          make dependencies
          make build_production
          sudo chown -R runner:docker .
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1